/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
<<<<<<< HEAD
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      items: ['intro', 'api'],
    },
    {
      type: 'category',
      label: 'System Status',
      items: ['status'],
    },
    {
      type: 'category',
      label: 'Legal',
      items: ['license', 'privacy', 'terms'],
    },
  ],
=======
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
>>>>>>> 71c525b4c2247256a3563b1760f4d079f362ecdc
};
