name: License & Header Check

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  license-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Check LICENSE.md exists
      run: |
        if [ ! -f "LICENSE.md" ]; then
          echo "❌ LICENSE.md not found"
          exit 1
        fi
        echo "✅ LICENSE.md found"
        
    - name: Check corporate entity in LICENSE.md
      run: |
        if ! grep -q "Zeropoint Protocol, Inc., a Texas C Corporation with principal offices in Austin, TX" LICENSE.md; then
          echo "❌ Corporate entity not found in LICENSE.md"
          exit 1
        fi
        echo "✅ Corporate entity found in LICENSE.md"
        
    - name: Check legal contact in LICENSE.md
      run: |
        if ! grep -q "legal@zeropointprotocol.ai" LICENSE.md; then
          echo "❌ Legal contact not found in LICENSE.md"
          exit 1
        fi
        echo "✅ Legal contact found in LICENSE.md"
        
    - name: Check TypeScript file headers
      run: |
        echo "Checking TypeScript file headers..."
        missing_headers=0
        for file in $(find . -name "*.ts" -not -path "./node_modules/*" -not -path "./dist/*"); do
          if ! head -1 "$file" | grep -q "© 2025 Zeropoint Protocol, Inc., a Texas C Corporation"; then
            echo "❌ Missing header in: $file"
            missing_headers=$((missing_headers + 1))
          fi
        done
        
        if [ $missing_headers -gt 0 ]; then
          echo "❌ Found $missing_headers files with missing headers"
          exit 1
        fi
        echo "✅ All TypeScript files have correct headers"
        
    - name: Check legal documents exist
      run: |
        for doc in ZAA.md CLA.md CONTRIBUTING.md LEGAL.md; do
          if [ ! -f "$doc" ]; then
            echo "❌ $doc not found"
            exit 1
          fi
          echo "✅ $doc found"
        done
        
    - name: Check README.md license section
      run: |
        if ! grep -q "© 2025 Zeropoint Protocol, Inc., a Texas C Corporation" README.md; then
          echo "❌ Corporate entity not found in README.md"
          exit 1
        fi
        if ! grep -q "legal@zeropointprotocol.ai" README.md; then
          echo "❌ Legal contact not found in README.md"
          exit 1
        fi
        echo "✅ README.md license section is correct"
        
    - name: Report success
      run: |
        echo "🎉 All license and header checks passed!"
        echo "✅ LICENSE.md: Corporate entity and contact verified"
        echo "✅ TypeScript headers: All files have correct headers"
        echo "✅ Legal documents: All required documents present"
        echo "✅ README.md: License section properly formatted"
